### ISSUE TITLE
Building issues of CUDA part on Linux..

### ISSUE THREAD

**Issue by oscarbg** [b0nes164/GPUSorting#11]
Hi,
trying to build under Ubuntu 24.10:
>nvcc -ccbin g++-13 Sort/DeviceRadixSort.cu Sort/EmulatedDeadlocking.cu Sort/OneSweep.cu GPUSortingCUDA.cu

using cuda 12.6.x:
>Cuda compilation tools, release 12.6, V12.6.85

I get this errors:
1)  #pragma unroll BIN_KEYS_PER_THREAD-> error: identifier "BIN_KEYS_PER_THREAD" is undefined
all Sort/DeviceRadixSort.cu Sort/EmulatedDeadlocking.cu Sort/OneSweep.cu
for example:
```
Sort/EmulatedDeadlocking.cu(414): error: identifier "BIN_KEYS_PER_THREAD" is undefined
  #pragma unroll BIN_KEYS_PER_THREAD
                 ^
Sort/EmulatedDeadlocking.cu(414): warning #20169-D: the optional argument to the unroll pragma must be an integral constant expression, ignoring pragma for this loop
  #pragma unroll BIN_KEYS_PER_THREAD
```
FIX:
> #pragma unroll BIN_KEYS_PER_THREAD change to #pragma unroll 15

2)
```
GPUSortingCUDA.cu(54): error: class "SplitSortTests<uint32_t>" has no member "TestAllRandomSegmentLengths"
      splitSort->TestAllRandomSegmentLengths<32>(100, false);

```
FIX: I comment this line of code for the moment..
>    //splitSort->TestAllRandomSegmentLengths<32>(100, false);

3) finally this bug:
lots of similar:
>error: identifier "LoadDirectWarpStriped" is undefined
```
/usr/local/cuda/bin/../targets/x86_64-linux/include/cub/agent/agent_radix_sort_onesweep.cuh(304): error: identifier "LoadDirectWarpStriped" is undefined
        LoadDirectWarpStriped(threadIdx.x, d_keys_in + tile_offset, keys);
```
others:
```
/usr/local/cuda/bin/../targets/x86_64-linux/include/cub/agent/agent_radix_sort_onesweep.cuh(328): error: identifier "LoadDirectWarpStriped" is undefined
        LoadDirectWarpStriped(threadIdx.x, d_values_in + tile_offset, values, tile_items);
        ^
          detected during:
```

**Comment by b0nes164** [comment]
Try the cleanup branch: https://github.com/b0nes164/GPUSorting/tree/cleanup.

Comment out the CUB and SplitSort, headers and tests. I think that should work, but I have not built this specifically on Linux.

sample makefile:
```
ARCH?=native
NVFLAGS=-std=c++14 -arch=$(ARCH) -O3 --expt-relaxed-constexpr --default-stream legacy 

all: main.out

main.out: GPUSortingCUDA.cu
	nvcc $(CXXFLAGS) $(NVFLAGS) $(INCLUDES) GPUSortingCUDA.cu -o main.out

clean:
	$(RM) main.out
```

**Comment by b0nes164** [comment]
Yea just tried this on Ubuntu 24.04 CUDA Toolkit 12.5; it _should_ be good, but you'll also have to comment out the asserts in [`OneSweepDispatcher.cuh`](https://github.com/b0nes164/GPUSorting/blob/fba8ea6abfd082c360cf3427f2d58e2bb02becad/GPUSortingCUDA/Sort/OneSweepDispatcher.cuh#L47) and [`DeviceRadixSortDispatcher.cuh`](https://github.com/b0nes164/GPUSorting/blob/fba8ea6abfd082c360cf3427f2d58e2bb02becad/GPUSortingCUDA/Sort/DeviceRadixSortDispatcher.cuh#L45). 

If you want to run the CUB tests or SplitSort, which uses CUB for testing, you'll have to link CUB.

**Comment by oscarbg** [comment]
thanks will take a look..

**Comment by oscarbg** [comment]
two things to note:
1) still one bug for me to fix:
```
SegSort/SplitSortTests.cuh:43:11: error: declaration of template parameter ‘K’ shadows template parameter
   43 |     template <class K>
      |           ^~~~~
SegSort/SplitSortTests.cuh:28:11: note: template parameter ‘K’ declared here
   28 | template <class K>
```
changed in line 43 K to K2:
 ```
  public:
    template <class K2>
    SplitSortTests(uint32_t maxTotalLength, uint32_t maxTotalSegCount, K dummy)
```
2) deleting -arch=$(ARCH) in makefile results in vastly better perf..

```
Beginning GPUSorting DeviceRadixSort pairs batch timing test at:
Estimated speed at 268435456 32-bit elements: 5.182168E+09 keys/sec

Beginning GPUSorting DeviceRadixSort pairs batch timing test at:
Total time elapsed: 0.000270
Estimated speed at 268435456 32-bit elements: 9.930875E+13 keys/sec
```
validation is OK..

**Comment by oscarbg** [comment]
3. I tested CUB (#include <cub.cuh> and -I /usr/local/cuda/include/cub) and also is working so closing..
thanks..

**Comment by b0nes164** [comment]
Deleting -arch=$(ARCH) is breaking compilation; a speed of 10^13 is theoretically impossible.
