### ISSUE TITLE
Performance on D3D12 on RTX 4070 lower than expected..

### ISSUE THREAD

**Issue by oscarbg** [b0nes164/GPUSorting#12]
Hi,
running the default app (removing passed tests) I was expecting performance at least equal to 2080 SUPER having at least similar bandwith and ALU and tex power..

>https://www.techpowerup.com/gpu-specs/geforce-rtx-2080-super.c3439
>https://www.techpowerup.com/gpu-specs/geforce-rtx-4070.c3924

you show almost 1e+10 in OneSweep and I'm getting 6.569906E+09 keys/sec for example..

some optimizations left, possible for Ada GPUs?
using 4070 latest 566.45 driver
```
GPUSortingD3D12.exe

Beginning DeviceRadixSort keys uint32 payload uint32 ascending batch timing test at:
Size: 268435456
Entropy: 1.000000 bits
Test size: 100
.............
Total time elapsed: 4.912779
Estimated speed at 268435456 32-bit elements: 5.464025E+09 keys/sec

Beginning OneSweep keys uint32 payload uint32 ascending batch timing test at:
Size: 268435456
Entropy: 1.000000 bits
Test size: 100
.............
Total time elapsed: 4.085834
Estimated speed at 268435456 32-bit elements: 6.569906E+09 keys/sec

Beginning FFXParallelSort keys uint32 payload uint32 ascending batch timing test at:
Size: 33554432
Entropy: 1.000000 bits
Test size: 100
.............
Total time elapsed: 1.295708
Estimated speed at 33554432 32-bit elements: 2.589659E+09 keys/sec
```

**Comment by b0nes164** [comment]
- You are comparing the performance of key/value pairs to keys only.
- D3D12 performance cannot be compared directly to CUDA. CUDA has adaptations like CUDA stream that can increase performance.
- The current tuning parameters are guesses, and you can try playing with it to find a better tuning parameter set.
