### ISSUE TITLE
Possible incorrect sorting on Wave Size 128

### ISSUE THREAD

**Issue by b0nes164** [b0nes164/GPUSorting#3]
See https://github.com/aras-p/UnityGaussianSplatting/issues/112

**Comment by b0nes164** [comment]
As stated on the README, I have tested on wave size 64.

**Comment by alasin** [comment]
Was it on an AMD GPU? Or Qualcomm Adreno?

**Comment by alasin** [comment]
I usually use [gpuinfo](https://vulkan.gpuinfo.org/listdevices.php) to check subgroup support in Vulkan for Qualcomm devices. Subgroup ops correspond one-to-one to wave ops in most cases. I also have a Quest 3 for which subgroup size is 64 (not sure if it can be changed to 128). If you need help in testing, I'd be happy to help debug.

**Comment by alasin** [comment]
> Do you know if it is possible to run this implementation on a Windows PC, using the Quest 3's Qualcomm chip as the device? 
I doubt it, or at least I haven't seen it done before. It should be possible through Unity though. Looks like you're already on top of it!

**Comment by LeeSYSU** [comment]
You can try change `waveFlags &= t ? ballot : ~ballot;` to `waveFlags &= (t ? ballot : (~ballot));` in function WarpLevelMultiSplitWGE16, this can show small models.

**Comment by b0nes164** [comment]
Closing this issue, as I have confirmed the bug does not have to do with the wave size. @LeeSYSU, copying your comment to #4.
