### ISSUE TITLE
WGPU support?

### ISSUE THREAD

**Issue by alienself** [b0nes164/GPUSorting#6]
Hi!

I saw with surprise that you added support for WGPU to your [`GPUPrefixSums`](https://github.com/b0nes164/GPUPrefixSums) repo,
does it mean that we could get a WGPU optimized sorting version in this repository?

Thanks!

**Comment by b0nes164** [comment]
In the future, yes. For now, no. I also really need to warn that the WGPU implementation on `GPUPrefixSums` is testing *only* and is incomplete. If you are using it as if it is fully portable/wave agnostic, it's not there yet.
