### ISSUE TITLE
Benchmarks across more devices

### ISSUE THREAD

**Issue by vassvik** [b0nes164/GPUSorting#7]
I've found this repository incredibly useful as a reference to evaluate my own exploration of GPU based sorting algorithms, especially with how easy it is to compile and get running. 

And while the benchmark values in the description are very useful, and I can still trivially run it on my own devices, it could be useful to open up a way for people to submit simple standardized benchmarks for different devices to quickly get an idea about how it scales across GPU architectures and specifications. 

Perhaps leveraging Github Discussions could allow people to benchmark and discuss the results on different GPUs, which could then regularly be collated into some summarized table somewhere?

**Comment by b0nes164** [comment]
I like this idea a lot. Technically, the code is ready to go right now, but I think it would be even easier if I wrapped the tests in a single function. That way users wouldn't have to deal with mucking around with the `ENTROPY_PRESETS`. I've been meaning to cleanup the CUDA version a little, so I think I'll hit that at the same time.

**Comment by b0nes164** [comment]
Ok I've opened up the discussion and added the benchmark. Thanks!

**Comment by vassvik** [comment]
Nice!

Some more suggestions:

A single function sounds like the best approach, should make it easier to "standardize".

As with any benchmarking it's hard to know where to draw the line in terms of what's of interest and how many permutations of inputs you'd want to look at, but I do think the current setup just focusing on a single large size for a the different entropy presets is a bit limiting. 

Interestingly on my GPU (a 4090) there's barely any difference between the entropy presets, and it's effectively entirely bandwidth bound (key-value pairs take twice as long as just keys).

A table with size per row and entropy preset per column would probably be ideal in terms of coverage, starting from 1<<10 and going up to 1<<28 or somesuch. The total time to test shouldn't increase that much, since it's the higher sizes that tend to dominate.

Then you could make one table containing raw time (divided by the batch size), effective bandwidth and key throughput, each of which would be useful to evaluate things in different ways. It'll end up being 6 tables per benchmark, but the output could and probably should be compacted quite nicely into two tables, one for keys-only and one for key-values.

**Comment by b0nes164** [comment]
> Interestingly on my GPU (a 4090) there's barely any difference between the entropy presets, and it's effectively entirely bandwidth bound (key-value pairs take twice as long as just keys).

As I understand it, a graphics card's sensitivity to low entropy distributions is determined by the speed of its atomics and its ability to tolerate shared memory bank conflicts during the histogramming and multisplitting. I've heard that Nvidia has been making strides in both of these areas, so this tracks. As you can see from my own data, my 2080 Super is hit pretty hard by low ent, so it's definitely something to keep in mind if you're targetting a more general consumer base.

> As with any benchmarking it's hard to know where to draw the line in terms of what's of interest and how many permutations of inputs you'd want to look at, but I do think the current setup just focusing on a single large size for a the different entropy presets is a bit limiting.

Absolutely. I don't think its necessary to track the entropy response across all the input sizes. Instead I'm thinking entropy tested at 2^28, and then tests across the input sizes at max ent (random distribution)?
